version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cti-postgres
    restart: always
    environment:
      POSTGRES_USER: cti
      POSTGRES_PASSWORD: cti
      POSTGRES_DB: cti
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

